/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        accent:           'rgb(var(--accent) / <alpha-value>)',
        'accent-fg':      'rgb(var(--accent-fg) / <alpha-value>)',
        success:          'rgb(var(--success) / <alpha-value>)',
        warning:          'rgb(var(--warning) / <alpha-value>)',
        danger:           'rgb(var(--danger) / <alpha-value>)',
        sidebar:          'rgb(var(--sidebar-bg) / <alpha-value>)',
        'sidebar-bg':     'rgb(var(--sidebar-bg) / <alpha-value>)',
        surface:          'rgb(var(--surface) / <alpha-value>)',
        primary:          'rgb(var(--primary-bg) / <alpha-value>)',
        'primary-bg':     'rgb(var(--primary-bg) / <alpha-value>)',
        'text-primary':   'rgb(var(--text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--text-secondary) / <alpha-value>)',
        'border-dark':    'rgb(var(--border-dark) / <alpha-value>)',
        'forest-700':     'rgb(var(--forest-700) / <alpha-value>)',
        'navy-900':       'rgb(var(--navy-900) / <alpha-value>)',
        'teal-50':        'rgb(var(--teal-50) / <alpha-value>)',

        // ----- legacy MFG-only tokens (preserved so existing pages compile) -----
        forest: {
          DEFAULT: '#1B5E20',
          50:  '#E8F5E9',
          100: '#C8E6C9',
          200: '#A5D6A7',
          300: '#81C784',
          400: '#4CAF50',
          500: '#2E7D32',
          600: '#1B5E20',
          700: '#155724',
          800: '#0A3D0A',
          900: '#052105',
        },
        green: {
          btn:    '#2E7D32',
          active: '#1B5E20',
          badge:  '#4CAF50',
          light:  '#E8F5E9',
        },
        card:   '#FFFFFF',
        border: '#E0E0E0',
        text: {
          primary:   'rgb(var(--text-primary) / <alpha-value>)',
          secondary: 'rgb(var(--text-secondary) / <alpha-value>)',
          muted:     '#9E9E9E',
          link:      '#1B5E20',
        },
        status: {
          running:     '#4CAF50',
          stopped:     '#D32F2F',
          delayed:     '#F57C00',
          maintenance: '#78909C',
          starved:     '#9E9E9E',
          offline:     '#BDBDBD',
        },
        alert: {
          critical: '#B71C1C',
          high:     '#C62828',
          p1:       '#B71C1C',
          p2:       '#D32F2F',
          p3:       '#F57C00',
          p4:       '#9E9E9E',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'label':      ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'body-xs':    ['12px', { lineHeight: '16px' }],
        'body-sm':    ['13px', { lineHeight: '20px' }],
        'body':       ['14px', { lineHeight: '20px' }],
        'body-md':    ['15px', { lineHeight: '22px' }],
        'heading-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'heading-md': ['18px', { lineHeight: '28px', fontWeight: '700' }],
        'heading-lg': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'heading-xl': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display':    ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'kpi':        ['36px', { lineHeight: '44px', fontWeight: '700' }],
      },
      boxShadow: {
        card:         '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.05)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.12)',
        andon:        '0 0 0 2px #D32F2F, 0 4px 16px rgba(211,47,47,0.3)',
      },
      animation: {
        'pulse-red': 'pulse 1s cubic-bezier(0.4,0,0.6,1) infinite',
        blink:       'blink 1.5s step-end infinite',
      },
      keyframes: {
        blink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.2' } },
      },
    },
  },
  plugins: [],
}
